return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter').install({
      'tsx',
      'typescript',
      'gitignore',
      'bash',
      'c',
      'rust',
      'go',
      'toml',
      'json',
      'yaml',
      'css',
      'scss',
      'html',
      'prisma',
      'svelte',
      'php',
      'python',
      'gomod',
      'gowork',
      'gosum',
      'lua',
      'vim',
      'vimdoc',
      'query',
      'markdown',
      'markdown_inline',
      'regex',
    })
  end,
}
