#!/usr/bin/env bash

setup_colors() {
  if [[ -t 2 ]] && [[ "${TERM-}" != "dumb" ]]; then
    # Color codes
    RED='\033[1;31m'
    YELLOW='\033[1;33m'
    BLUE="\\033[38;5;27m"
    SEA="\\033[38;5;49m"
    GREEN='\033[1;32m'
    CYAN='\033[1;36m'
    NC='\033[0m'

    # Emoji codes
    CHECK_MARK="${GREEN}\xE2\x9C\x94${NC}"
    X_MARK="${RED}\xE2\x9C\x96${NC}"
    PIN="${RED}\xF0\x9F\x93\x8C${NC}"
    CLOCK="${GREEN}\xE2\x8C\x9B${NC}"
    ARROW="${SEA}\xE2\x96\xB6${NC}"
    BOOK="${RED}\xF0\x9F\x93\x8B${NC}"
    HOT="${ORANGE}\xF0\x9F\x94\xA5${NC}"
    WARNING="${GREEN}\xF0\x9F\x9A\xA8${NC}"
    RIGHT_ANGLE="${GREEN}\xE2\x88\x9F${NC}"
  else
    RED='' YELLOW='' BLUE='' SEA='' GREEN='' CYAN='' NC='' CHECK_MARK='' X_MARK='' PIN='' CLOCK='' ARROW='' BOOK='' HOT='' WARNING='' RIGHT_ANGLE=''
  fi
}

exists() {
  local testing_command="$1"

  if command -v $testing_command 2>&1 >/dev/null; then
    echo 0
  else
    echo 1
  fi
}

clone_repo() {
  echo "Cloning repo..."
  git clone https://github.com/epicmet/.dotfiles "$HOME/.dotfiles"
}

install_deps_arch() {
  echo "Installing arch deps..."

  if [[ $(exists pacman) == 1 ]]; then
    echo -e "${RED} Could not find pacman in your \$PATH!${NC}"
    exit 1
  fi

  sudo pacman -Syu

  sudo pacman -S \
    git \
    base-devel \
    curl \
    openssl \
    gum \
    neovim \
    tmux \
    tree-sitter \
    zsh \
    lua \
    luarocks \
    stow \
    fzf \
    starship \
    fd \
    ripgrep \
    jq \
    zoxide \
    bat \
    dua-cli \
    bpytop \
    ttf-dejavu \
    ttf-cascadia-code-nerd \
    rbw \
    docker \
    ansible-core \
    lazygit \
    wezterm \
    eza \
    i3-wm \
    inkscape \
    ghostty \
    gnome-keyring \
    rofi \
    sshuttle \
    go \
    xsel \
    less \
    man-db \
    arandr \
    yazi

  mkdir -p "$HOME/Software"
  git clone https://aur.archlinux.org/paru.git "$HOME/Software/paru" --depth=1
  pushd "$HOME/Software/paru"
  makepkg -si

  echo "Installing AURs ..."
  paru -S \
    lazydocker \
    brave-bin \
    yq \
    boomer \
    waypaper \
    rofi-greenclip

  popd

  # TPM
  git clone https://github.com/tmux-plugins/tmp ~/.tmux/plugins/tpm

  # NVM
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash

  # Gauth
  go install github.com/pcarrier/gauth@latest
}

install_deps_mac() {
  # TODO: Figure something out for MacOS
  echo "MacOS Auto install deps NOT IMPLEMENTED! You are on your own..."
}

install_deps() {
  while true; do
    local prompt="Choose OS (1: archliux, 2: MacOS): "
    read -p "$prompt" choice

    case $choice in
    '1')
      install_deps_arch
      break
      ;;
    '2')
      install_deps_mac
      break
      ;;
    *)
      echo "invalid choice!"
      echo
      ;;
    esac
  done
}

main() {
  setup_colors

  if [[ $(exists dot) == 0 ]]; then
    echo -e "${RED} There is already a \'dot\' executable found in your \$PATH!${NC}"
    exit 1
  fi

  install_deps

  clone_repo

  pushd "$HOME/.dotfiles"
  ./dot sync
  ./dot init
  popd
}

main

exit 0
