#!/bin/bash

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="bin,zsh,nvim,tmux,yabai,starship"
fi

if [[ -z $DOT_FILES ]]; then
  DOT_FILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOT_FILES=$DOT_FILES $DOT_FILES/init
