- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - initial
    - ssh
- name: Copy private ssh key
  copy:
    src: "{{ ssh_source_key }}"
    dest: "{{ ssh_dest_key }}"
    mode: 0600
  tags:
    - initial
    - ssh
- name: Copy public ssh key
  copy:
    src: "{{ ssh_source_key }}.pub"
    dest: "{{ ssh_dest_key }}.pub"
    mode: 0644
  tags:
    - initial
    - ssh
- name: Copy ssh config
  copy:
    src: "{{ ssh_config_source }}"
    dest: "{{ ssh_config_dest }}"
    mode: 0644
  tags:
    - initial
    - ssh
